[workspace]

members = [
    "dcompass",
    "dmatcher",
    "droute",
]

[profile.release]
lto = true
opt-level = 's'
codegen-units = 1
panic = "abort"

[patch.crates-io]
governor = { git = "https://github.com/antifuchs/governor", branch = "master" }

