---
verbosity: warn
address: 0.0.0.0:2053

table:
  start:
    if:
      qtype:
        - AAAA
    then:
      # force disable IPv6
      - blackhole
      - end
    else:
      - dispatch
  dispatch:
    if:
      domain:
        - qname: ytimg.com
        - qname: youtube.com
        - qname: 1e100.net
        - qname: gvt1.com
        - qname: gvt2.com
        - qname: ggpht.com
        - qname: google.com
        - qname: gstatic.com
        - qname: googleapis.com
        - qname: googlevideo.com
        - qname: googleusercontent.com
        - qname: googlesyndication.com
        - qname: g.cn
        - qname: gkecnapps.cn
        - qname: googleapis.cn
        - qname: googlecnapps.cn
        - qname: gstaticcnapps.cn
        - qname: googleadsserving.cn
    then:
      # force all google query with secure to avoid AS24424
      - query: secure
      - end
    else:
      - query: domestic
      - check_secure
  check_secure:
    if:
      # geoip:
      #   codes:
      #     - CN
      ipcidr:
        - ../data/ipcn.txt.gz
    else:
      - query: secure
      - end

upstreams:
  dnspodDoH:
    https:
      addr: https://162.14.21.56:443/dns-query

  aliDoH:
    https:
      addr: https://223.5.5.5/dns-query

  googleDoH:
    https:
      addr: https://8.8.4.4/dns-query

  quad9DoH:
    https:
      addr: https://149.112.112.112:443/dns-query

  cloudflareDoH:
    https:
      addr: https://162.159.36.1:443/dns-query

  # ------------ FINAL -------------

  domestic:
    hybrid:
      - dnspodDoH
      - aliDoH

  secure:
    hybrid:
      - googleDoH
      - quad9DoH
      - cloudflareDoH
