---
verbosity: "info"
address: 0.0.0.0:2053
table:
  start:
    if: |
      qtype([AAAA, SOA]) && (!(!true)) && (true || (!true))
    then:
      # A list of actions is allowed here
      - blackhole
      # The next tag to go
      - end
    else:
      - query: Ali
      - end

upstreams:
  Ali:
    udp:
      addr: 223.6.6.6:53
