---
verbosity: "off"
address: 0.0.0.0:2053
table:
  start:
    if: |
      domain([file("../data/china.txt")])
    then:
      - query: domestic
      - end
    else:
      - query:
          tag: secure
          cache_policy: persistent
      - end
upstreams:
  domestic:
    udp:
      addr: 114.114.114.114:53
      timeout: 1
  secure:
    https:
      timeout: 2
      uri: https://dns.quad9.net/dns-query
      addr: 9.9.9.9
