[package]
name = "dcompass"
version = "0.1.0-alpha.1"
authors = ["Harry Ying <lexugeyky@outlook.com>"]
edition = "2018"
description = "Rule-based high performance DNS server with multi-upstreams, DoT and DoH supports."
repository = "https://github.com/LEXUGE/dcompass"
license = "GPL-3.0"

[features]
geoip-cn = []
geoip-maxmind = []

[dependencies]
async-trait = "^0.1"
domain = {version = "^0.6", features = ["bytes"]}
droute = {version = "0.1.0-alpha.1", path = "../droute", features = ["full", "vendored"]}
futures = "^0.3"
tokio = { version = "^1.3", features = ["rt-multi-thread", "net", "fs", "macros", "io-util", "signal"]}
simple_logger = "^1.11"
log = "^0.4"
anyhow = "^1.0"
serde = { version = "^1.0", features = ["derive", "rc"] }
serde_yaml = "^0.8"
dmatcher = {version = "^0.1", path = "../dmatcher"}
structopt = "^0.3"
governor = {version = "0.3.3-dev", git = "https://github.com/antifuchs/governor"}
bytes = "^1"

# Both musl and msvc are not well-supoorted
# Only allow on gnu or none env AND not on windows
[target.'cfg(all(any(target_env = "gnu", target_env = ""), not(target_os = "windows")))'.dependencies]
tikv-jemallocator = {version = "^0.4", features = ["background_threads"]}

[dev-dependencies]
tokio-test = "^0.4"
